import type { Achievement, Challenge, DailyReward, SpinReward } from './types';

export const ACHIEVEMENTS_DATA: Achievement[] = [
    {
        id: 1,
        title: "First Steps",
        description: "Complete your first quiz",
        icon: "🌱",
        category: "Beginner",
        progress: 1,
        target: 1,
        completed: true,
        reward: { coins: 50, xp: 25 },
        rarity: "common",
    },
    {
        id: 2,
        title: "Category Explorer",
        description: "Complete a quiz in 3 different categories",
        icon: "🗺️",
        category: "Beginner",
        progress: 1,
        target: 3,
        completed: false,
        reward: { coins: 100, xp: 50 },
        rarity: "common",
    },
    {
        id: 3,
        title: "Quiz Novice",
        description: "Answer 25 questions correctly",
        icon: "🧠",
        category: "Progress",
        progress: 15,
        target: 25,
        completed: false,
        reward: { coins: 75, xp: 40 },
        rarity: "common",
    },
    {
        id: 4,
        title: "Perfect Score",
        description: "Get 100% on any quiz",
        icon: "🎯",
        category: "Excellence",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 150, xp: 100 },
        rarity: "uncommon",
    },
    {
        id: 5,
        title: "Daily Dedication",
        description: "Complete a quiz 3 days in a row",
        icon: "🗓️",
        category: "Dedication",
        progress: 2,
        target: 3,
        completed: false,
        reward: { coins: 200, xp: 75 },
        rarity: "uncommon",
    },
    {
        id: 6,
        title: "Knowledge Seeker",
        description: "Unlock the 'Talib' rank",
        icon: "🎓",
        category: "Mastery",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 250, xp: 120, title: "Knowledge Seeker" },
        rarity: "rare",
    }
];

export const DAILY_CHALLENGES_DATA: Challenge[] = [
    {
        id: 101,
        title: "Quran Quickfire",
        description: "Answer 5 questions in the 'Holy Quran' category",
        icon: "📖",
        progress: 2,
        target: 5,
        reward: { coins: 50, xp: 30 },
        timeLeft: "23:15:05",
        completed: false,
    },
    {
        id: 102,
        title: "Fiqh Focus",
        description: "Score at least 80% on a 'Fiqh' quiz",
        icon: "⚖️",
        progress: 0,
        target: 1,
        reward: { coins: 75, xp: 40 },
        timeLeft: "23:15:05",
        completed: false,
    },
];

export const WEEKLY_CHALLENGES_DATA: Challenge[] = [
    {
        id: 201,
        title: "Seerah Scholar",
        description: "Complete all quizzes in the 'Prophetic Biography' category",
        icon: "🕌",
        progress: 1,
        target: 4, // Assuming there are 4 quizzes
        reward: { coins: 500, xp: 250, badge: "Seerah Scholar Badge" },
        timeLeft: "6d 10h",
        completed: false,
    },
    {
        id: 202,
        title: "Master of Pillars",
        description: "Get a perfect score on a 'Five Pillars' quiz",
        icon: "🏛️",
        progress: 0,
        target: 1,
        reward: { coins: 300, xp: 150, badge: "Pillar Master Badge" },
        timeLeft: "6d 10h",
        completed: false,
    },
];

export const SPIN_REWARDS: SpinReward[] = [
  { id: 1, name: "50 Coins", icon: "🪙", probability: 30, value: 50, type: "coins" },
  { id: 2, name: "25 XP", icon: "⭐", probability: 25, value: 25, type: "xp" },
  { id: 3, name: "100 Coins", icon: "💰", probability: 20, value: 100, type: "coins" },
  { id: 4, name: "Lifeline", icon: "💡", probability: 15, value: 1, type: "lifeline" },
  { id: 5, name: "500 Coins", icon: "💎", probability: 8, value: 500, type: "coins" },
  { id: 6, name: "Rare Badge", icon: "🏆", probability: 2, value: 1, type: "badge" },
];

export const DAILY_REWARDS: DailyReward[] = [
  { day: 1, coins: 50, xp: 25, bonus: null },
  { day: 2, coins: 75, xp: 35, bonus: null },
  { day: 3, coins: 100, xp: 50, bonus: "Lifeline x1" },
  { day: 4, coins: 125, xp: 60, bonus: null },
  { day: 5, coins: 150, xp: 75, bonus: null },
  { day: 6, coins: 200, xp: 100, bonus: "Double XP (1hr)" },
  { day: 7, coins: 500, xp: 250, bonus: "Exclusive Badge" },
];
