import type { Achievement, Challenge, DailyReward, SpinReward } from './types';

export const ACHIEVEMENTS_DATA: Achievement[] = [
    {
        id: 1,
        title: "First Steps",
        description: "Complete your first quiz",
        icon: "🌱",
        category: "Beginner",
        progress: 1,
        target: 1,
        completed: true,
        reward: { coins: 50, xp: 25 },
        rarity: "common",
    },
    {
        id: 2,
        title: "Category Explorer",
        description: "Complete a quiz in 3 different categories",
        icon: "🗺️",
        category: "Beginner",
        progress: 1,
        target: 3,
        completed: false,
        reward: { coins: 100, xp: 50 },
        rarity: "common",
    },
    {
        id: 3,
        title: "Quiz Novice",
        description: "Answer 25 questions correctly",
        icon: "🧠",
        category: "Progress",
        progress: 15,
        target: 25,
        completed: false,
        reward: { coins: 75, xp: 40 },
        rarity: "common",
    },
    {
        id: 4,
        title: "Perfect Score",
        description: "Get 100% on any quiz",
        icon: "🎯",
        category: "Excellence",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 150, xp: 100 },
        rarity: "uncommon",
    },
    {
        id: 5,
        title: "Daily Dedication",
        description: "Complete a quiz 3 days in a row",
        icon: "🗓️",
        category: "Dedication",
        progress: 2,
        target: 3,
        completed: false,
        reward: { coins: 200, xp: 75 },
        rarity: "uncommon",
    },
    {
        id: 6,
        title: "Knowledge Seeker",
        description: "Unlock the 'Talib' rank",
        icon: "🎓",
        category: "Mastery",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 250, xp: 120, title: "Knowledge Seeker" },
        rarity: "rare",
    },
    {
        id: 7,
        title: "Hadith Enthusiast",
        description: "Answer 50 questions in the Hadith category",
        icon: "📜",
        category: "Progress",
        progress: 20,
        target: 50,
        completed: false,
        reward: { coins: 150, xp: 80 },
        rarity: "uncommon",
    },
    {
        id: 8,
        title: "Fiqh Apprentice",
        description: "Complete your first Fiqh (Islamic Law) quiz",
        icon: "⚖️",
        category: "Beginner",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 100, xp: 50 },
        rarity: "uncommon",
    },
    {
        id: 9,
        title: "Seerah Storyteller",
        description: "Complete 5 quizzes on Prophetic Biography",
        icon: "⭐",
        category: "Progress",
        progress: 1,
        target: 5,
        completed: false,
        reward: { coins: 200, xp: 100 },
        rarity: "rare",
    },
    {
        id: 10,
        title: "Sharpshooter",
        description: "Achieve 90% accuracy across 10 quizzes",
        icon: "🏹",
        category: "Excellence",
        progress: 2,
        target: 10,
        completed: false,
        reward: { coins: 300, xp: 150 },
        rarity: "rare",
    },
    {
        id: 11,
        title: "Lifeline User",
        description: "Use a lifeline for the first time",
        icon: "💡",
        category: "Gameplay",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 25, xp: 10 },
        rarity: "common",
    },
    {
        id: 12,
        title: "Grandmaster",
        description: "Reach the rank of 'Imam'",
        icon: "👑",
        category: "Mastery",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 1000, xp: 500, title: "Grandmaster" },
        rarity: "epic",
    },
    {
        id: 13,
        title: "Quiz Marathoner",
        description: "Answer 500 questions correctly",
        icon: "🏃",
        category: "Progress",
        progress: 87,
        target: 500,
        completed: false,
        reward: { coins: 500, xp: 250 },
        rarity: "rare",
    },
    {
        id: 14,
        title: "Unstoppable",
        description: "Maintain a 7-day learning streak",
        icon: "🔥",
        category: "Dedication",
        progress: 7,
        target: 7,
        completed: true,
        reward: { coins: 400, xp: 200 },
        rarity: "rare",
    },
    {
        id: 15,
        title: "Wise Spender",
        description: "Purchase an item from the store",
        icon: "🛍️",
        category: "Gameplay",
        progress: 0,
        target: 1,
        completed: false,
        reward: { coins: 30, xp: 15 },
        rarity: "common",
    }
];

export const DAILY_CHALLENGES_DATA: Challenge[] = [
    {
        id: 101,
        title: "Quran Quickfire",
        description: "Answer 5 questions in the 'Holy Quran' category",
        icon: "📖",
        progress: 2,
        target: 5,
        reward: { coins: 50, xp: 30 },
        timeLeft: "23:15:05",
        completed: false,
    },
    {
        id: 102,
        title: "Fiqh Focus",
        description: "Score at least 80% on a 'Fiqh' quiz",
        icon: "⚖️",
        progress: 0,
        target: 1,
        reward: { coins: 75, xp: 40 },
        timeLeft: "23:15:05",
        completed: false,
    },
    {
        id: 103,
        title: "Seerah Speedrun",
        description: "Answer 3 questions about Prophets in under a minute total.",
        icon: "⭐",
        progress: 0,
        target: 3,
        reward: { coins: 60, xp: 35 },
        timeLeft: "23:15:05",
        completed: false,
    },
    {
        id: 104,
        title: "Streak Starter",
        description: "Get a 5-question answer streak.",
        icon: "🔥",
        progress: 3,
        target: 5,
        reward: { coins: 80, xp: 50 },
        timeLeft: "23:15:05",
        completed: false,
    }
];

export const WEEKLY_CHALLENGES_DATA: Challenge[] = [
    {
        id: 201,
        title: "Seerah Scholar",
        description: "Complete all quizzes in the 'Prophetic Biography' category",
        icon: "🕌",
        progress: 1,
        target: 4,
        reward: { coins: 500, xp: 250, badge: "Seerah Scholar Badge" },
        timeLeft: "6d 10h",
        completed: false,
    },
    {
        id: 202,
        title: "Master of Pillars",
        description: "Get a perfect score on a 'Five Pillars' quiz",
        icon: "🏛️",
        progress: 0,
        target: 1,
        reward: { coins: 300, xp: 150, badge: "Pillar Master Badge" },
        timeLeft: "6d 10h",
        completed: false,
    },
    {
        id: 203,
        title: "Knowledge Marathon",
        description: "Answer 100 questions correctly throughout the week.",
        icon: "🏃",
        progress: 34,
        target: 100,
        reward: { coins: 600, xp: 300, badge: "Marathoner" },
        timeLeft: "6d 10h",
        completed: false,
    },
    {
        id: 204,
        title: "Category Conqueror",
        description: "Complete a quiz in 5 different categories.",
        icon: "🗺️",
        progress: 2,
        target: 5,
        reward: { coins: 400, xp: 200 },
        timeLeft: "6d 10h",
        completed: false,
    }
];

export const SPIN_REWARDS: SpinReward[] = [
  { id: 1, name: "50 Coins", icon: "🪙", probability: 30, value: 50, type: "coins" },
  { id: 2, name: "25 XP", icon: "⭐", probability: 25, value: 25, type: "xp" },
  { id: 3, name: "100 Coins", icon: "💰", probability: 20, value: 100, type: "coins" },
  { id: 4, name: "Lifeline", icon: "💡", probability: 15, value: 1, type: "lifeline" },
  { id: 5, name: "500 Coins", icon: "💎", probability: 8, value: 500, type: "coins" },
  { id: 6, name: "Rare Badge", icon: "🏆", probability: 2, value: 1, type: "badge" },
];

export const DAILY_REWARDS: DailyReward[] = [
  { day: 1, coins: 50, xp: 25, bonus: null },
  { day: 2, coins: 75, xp: 35, bonus: null },
  { day: 3, coins: 100, xp: 50, bonus: "Lifeline x1" },
  { day: 4, coins: 125, xp: 60, bonus: null },
  { day: 5, coins: 150, xp: 75, bonus: null },
  { day: 6, coins: 200, xp: 100, bonus: "Double XP (1hr)" },
  { day: 7, coins: 500, xp: 250, bonus: "Exclusive Badge" },
];
