import type { LeaderboardUser, CategoryLeader } from './types';

export const GLOBAL_LEADERBOARD: LeaderboardUser[] = [
  {
    rank: 1,
    name: 'Aisha Al-Zahra',
    points: 15420,
    rank_title: 'Mujaddid',
    streak: 89,
    country: '🇸🇦',
    avatar: 'A',
    badge: '👑',
  },
  {
    rank: 2,
    name: 'Omar Abdullah',
    points: 14980,
    rank_title: 'Imam',
    streak: 75,
    country: '🇪🇬',
    avatar: 'O',
    badge: '🥈',
  },
  {
    rank: 3,
    name: 'Fatima Al-Fahim',
    points: 14500,
    rank_title: 'Shaykh',
    streak: 60,
    country: '🇲🇦',
    avatar: 'F',
    badge: '🥉',
  },
  {
    rank: 4,
    name: 'Yusuf Al-Andalusi',
    points: 13900,
    rank_title: 'Mufassir',
    streak: 55,
    country: '🇪🇸',
    avatar: 'Y',
  },
  {
    rank: 5,
    name: 'Zainab bint Ali',
    points: 13250,
    rank_title: 'Muhaddith',
    streak: 45,
    country: '🇮🇩',
    avatar: 'Z',
  },
];

export const WEEKLY_LEADERS: LeaderboardUser[] = [
  {
    rank: 1,
    name: 'Muhammad Al-Faqih',
    points: 2340,
    rank_title: 'Faqih',
    questionsAnswered: 156,
    country: '🇯🇴',
    avatar: 'M',
  },
  {
    rank: 2,
    name: 'Layla Al-Hakim',
    points: 2180,
    rank_title: 'Talib',
    questionsAnswered: 142,
    country: '🇹🇷',
    avatar: 'L',
  },
  {
    rank: 3,
    name: 'Ahmed Khan',
    points: 1990,
    rank_title: 'Hafiz',
    questionsAnswered: 130,
    country: '🇵🇰',
    avatar: 'A',
  },
];

export const CATEGORY_LEADERS: CategoryLeader[] = [
  {
    category: 'Holy Quran',
    icon: '📖',
    leader: 'Hafiz Yusuf',
    points: 3420,
    rank_title: 'Hafiz',
    country: '🇸🇦',
  },
  {
    category: 'Prophetic Biography',
    icon: '📜',
    leader: 'SeerahStudent',
    points: 3100,
    rank_title: 'Talib',
    country: '🇲🇾',
  },
  {
    category: 'Islamic Law (Fiqh)',
    icon: '⚖️',
    leader: 'FiqhExplorer',
    points: 2850,
    rank_title: 'Faqih',
    country: '🇳🇬',
  },
  {
    category: 'Five Pillars',
    icon: '🕌',
    leader: 'PillarPractitioner',
    points: 2500,
    rank_title: 'Mubtadi',
    country: '🇬🇧',
  },
];
